# judge_countries.py
# Daniele Bellutta
# 1 May 2020


JUDGE_COUNTRIES = {
  "ranjeva": "mg",
  "guillaume": "fr",
  "rezek": "br",
  "higgins": "gb",
  "buergenthal": "us",
  "kooijmans": "nl",
  "tomka": "sk",
  "owada": "jp",
  "shi": "cn",
  "vereshchetin": "ru",
  "al-khasawneh": "jo",
  "simma": "de",
  "elaraby": "eg",
  "parra-aranguren": "ve",
  "koroma": "sl",
  "rigaux": "be",
  "cançado trindade": "br",
  "sepúlveda-amor": "mx",
  "yusuf": "so",
  "keith": "nz",
  "greenwood": "gb",
  "bennouna": "ma",
  "skotnikov": "ru",
  "abraham": "fr",
  "hackworth": "us",
  "read": "ca",
  "carneiro": "br",
  "alvarez": "cl",
  "basdevant": "fr",
  "klaestad": "no",
  "badawi": "eg",
  "mcnair": "gb",
  "armand-ugon": "uy",
  "zoričić": "yu",
  "hsu mo": "cn",
  "rau": "in",
  "winiarski": "pl",
  "guerrero": "sv",
  "spiropoulos": "gr",
  "shahabuddeen": "gy",
  "ferrari bravo": "it",
  "oda": "jp",
  "herczegh": "hu",
  "weeramantry": "lk",
  "schwebel": "us",
  "fleischhauer": "de",
  "bedjaoui": "dz",
  "cot": "fr",
  "oxman": "us",
  "de visscher": "be",
  "sandjabi": "ir",
  "vinuesa": "ar",
  "torres bernárdez": "es",
  "krylov": "su",
  "caicedo castilla": "co",
  "alayza y paz soldan": "pe",
  "fabela": "mx",
  "azevedo": "br",
  "xue": "cn",
  "donoghue": "us",
  "gaja": "it",
  "fortier": "ca",
  "daxner": "cs",
  "pirzada": "pk",
  "reddy": "in",
  "roucounas": "gr",
  "vukas": "hr",
  "morelli": "it",
  "gros": "fr",
  "bengzon": "ph",
  "forster": "sn",
  "tanaka": "jp",
  "fitzmaurice": "gb",
  "lachs": "pl",
  "petrén": "se",
  "koretsky": "su",
  "bustamante y rivero": "pe",
  "jessup": "us",
  "onyeama": "ng",
  "ammoun": "lb",
  "padilla nervo": "mx",
  "riphagen": "nl",
  "nagendra singh": "in",
  "mbaye": "sn",
  "elias": "ng",
  "jennings": "gb",
  "ruda": "ar",
  "sette-camara": "br",
  "ago": "it",
  "de lacharriere": "fr",
  "morozov": "su",
  "el-khani": "sy",
  "mosler": "de",
  "spender": "au",
  "cordova": "mx",
  "moreno quintana": "ar",
  "wellington koo": "cn",
  "zafrulla khan": "pk",
  "kojevnikov": "su",
  "hersch lauterpacht": "gb",
  "carry": "ch",
  "zourek": "cs",
  "goitein": "il",
  "tarazi": "sy",
  "el-erian": "eg",
  "baxter": "us",
  "waldock": "gb",
  "muhammad zafrulla khan": "pk",
  "sørensen": "dk",
  "valticos": "gr",
  "jimenez de aréchaga": "uy",
  "evensen": "no",
  "ignacio-pinto": "bj",
  "dillard": "us",
  "de castro": "es",
  "cohen": "ca",
  "ni": "cn",
  "aguilar-mawdsley": "ve",
  "ajibola": "ng",
  "tarasov": "ru",
  "fischer": "dk",
  "mohammed bedjaoui": "dz",
  "abi-saab": "eg",
  "luchaire": "fr",
  "jose sette-camara": "br",
  "stassinopoulos": "gr",
  "barwick": "au",
  "mahiou": "dz",
  "mampuya": "cd",
  "boni": "ci",
  "singh": "in",
  "sebutinde": "ug",
  "mensah": "gh",
  "guggenheim": "ch",
  "garcia bauer": "gt",
  "alfaro": "pa",
  "lalonde": "ca",
  "jose maria ruda": "ar",
  "kirsch": "be",
  "sur": "fr",
  "urrutia holguín": "co",
  "pathak": "in",
  "stephen": "au",
  "skubiszewski": "pl",
  "thierry": "fr",
  "bhandari": "in",
  "daudet": "fr",
  "beb à don": "cm",
  "mbanefo": "ng",
  "van wyk": "za",
  "kreća": "rs",
  "colliard": "fr",
  "fernandes": "pt",
  "chagla": "in",
  "offerhaus": "nl",
  "sterzel": "se",
  "kateka": "tz",
  "verhoeven": "be",
  "lauterpacht": "gb",
  "bula-bula": "cd",
  "van den wyngaert": "be",
  "mavungu": "cd",
  "dugard": "za",
  "franck": "us",
  "el-kosheri": "eg",
  "rao": "in",
  "berman": "gb",
}

